### ISSUE TITLE
Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined

### ISSUE THREAD

**Issue by x22x22** [KoharaKazuya/tree-view-background#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.0-beta1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [tree-view-background](https://github.com/KoharaKazuya/tree-view-background) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined

```
At /Users/Kdump/.atom/packages/tree-view-background/lib/image-url-register-view.coffee:66

TypeError: Cannot read property 'showOpenDialog' of undefined
    at ImageUrlRegisterView.module.exports.ImageUrlRegisterView.open (/packages/tree-view-background/lib/image-url-register-view.coffee:66:19)
    at /packages/tree-view-background/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/tree-view-background/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/tree-view-background/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:07.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.editor-background.use-animations.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -0:47.8.0 command-palette:toggle (atom-pane.pane.active)
     -0:45.9.0 core:backspace (input.hidden-input)
  3x -0:44.2.0 core:move-down (input.hidden-input)
  2x -0:43.2.0 core:move-up (input.hidden-input)
     -0:42.7.0 core:confirm (input.hidden-input)
     -0:42.7.0 sync-settings:backup (atom-pane.pane.active)
     -0:32.2.0 command-palette:toggle (atom-pane.pane.active)
     -0:30.4.0 core:backspace (input.hidden-input)
 25x -0:26.6.0 core:move-down (input.hidden-input)
     -0:17.7.0 core:move-up (input.hidden-input)
     -0:12.7.0 core:confirm (input.hidden-input)
     -0:12.7.0 tree-view-background:register-image (atom-pane.pane.active)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
advanced-open-file 0.16.5 
angular-2-typeScript-snippets 0.6.3 
angular-bootstrap 1.0.1 
angular2-component-generator 0.0.1 
asciidoc-preview 2.7.1 
atom-beautify 0.29.16 
atom-bootstrap3 1.2.12 
atom-clock 0.1.3 
atom-image-resize 0.3.0 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
atom-ternjs 0.17.0 
atom-typescript 10.1.13 
atomatigit 1.5.5 
autoclose-html 0.23.0 
autocomplete-modules 1.6.7 
autocomplete-paths 1.0.5 
color-picker 2.2.4 
docblockr 0.9.1 
editor-background 1.2.37 
editorconfig 2.2.0 
emmet 2.4.3 
file-icons 2.0.10 
git-plus 7.1.1 
git-time-machine 1.5.4 
highlight-selected 0.12.0 
kde-breeze-dark-ui 1.0.0 
language-babel 2.49.4 
language-diff 0.7.0 
language-ejs 0.4.0 
language-jade 0.7.2 
language-vue 0.21.2 
linter 1.11.21 
linter-sass-lint 1.7.4 
linter-tidy 2.3.0 
linter-tslint 0.13.1 
linter-write-good 0.8.0 
merge-conflicts 1.4.4 
minimap 4.26.7 
minimap-find-and-replace 4.5.1 
minimap-highlight-selected 4.5.0 
node-debug 0.1.7 
node-debugger 1.10.0 
nord-atom-syntax 0.5.0 
nord-atom-ui 0.9.0 
pigments 0.38.0 
platformio-ide-terminal 2.2.2 
power-editor 0.1.1 
pretty-json 1.6.1 
project-folder 1.2.1 
qolor 0.4.1 
script 3.14.0 
seti-syntax 1.0.1 
seti-ui 1.4.0 
svg-preview 0.11.0 
sync-settings 0.8.1 
terminal-panel 1.14.1 
tree-view-background 0.4.0 
vim-mode 0.65.2 
zentabs 0.8.8 
```

**Comment by KoharaKazuya** [comment]
@x22x22 Thank you for your report!
Fixed version (v0.4.1) has released.
